### ISSUE TITLE
Cannot get tests to work

### ISSUE THREAD

**Issue by raphdamico** [Prozi/pixi-shim#16]
Hi Prozi—I followed all the instructions to install pixi-shim via yarn but when I run the tests I get the following output

```
raphdamico@Raphs-MacBook-Pro-2 pixi-shim-master-2 % node tests
pixi-shim ❤️ DOM
pixi-shim ❤️ Window 1024x768
pixi-shim ❤️ polyfill performance.now
pixi-shim ❤️ polyfill requestAnimationFrame
pixi-shim ❤️ PIXI.js
{ 'PIXI.Application': true }
{
  canvas: {
    getContext: [Function: getContext],
    toDataURL: [Function: toDataURL]
  }
}
{
  image: HTMLImageElement {
    [Symbol(SameObject caches)]: [Object: null prototype] { style: [CSSStyleDeclaration] }
  },
  context: {}
}
{ 'sprite dimensions': { width: 16, height: 16 } }
{ 'PIXI.Sprite.from': true }
{ base64: '', toDataURL: true }
{ FPS: '0.00' }
raphdamico@Raphs-MacBook-Pro-2 pixi-shim-master-2 % 
```

It just looks like it's silently failing. It doesn't seem like I'm missing anything so any help figuring out this issue would be incredibly appreciated.

**What is the expected output for this test?**

(I'm hoping to use pixi via pixi-shim to generate an animation on the server, export the frames and stitch them together into an animated GIF. Do you think pixi via pixi-shim has the basic features needed to make that work?)

**Comment by Prozi** [comment]
this is actually the correct output.

if you want to do what you want to do in node + pixi-shim i would do this like:

```
git clone https://github.com/Prozi/pixi-shim.git
```

then find the latest 1.X version but not 2.X

in 2.X because of multiple problems for people with installing this lib,

most features like window canvas etc are polyfilled but not really emulated.

in 1.X this was an attempt to emulate them. start with this. continue this thread if you will need any help.

@raphdamico

**Comment by arbaaz** [comment]
@Prozi Do you have any working example code?

**Comment by Prozi** [comment]
```
npm i pixi-shim -D
cd node_modules/pixi-shim
yarn
yarn test
```

will run

https://github.com/Prozi/pixi-shim/blob/master/index.spec.js

is this sufficient @arbaaz @raphdamico ?

**Comment by Prozi** [comment]
also https://app.circleci.com/pipelines/github/Prozi/pixi-shim

**Comment by Prozi** [comment]
Closing as resolved
