### ISSUE TITLE
toDataURL only show canvas backgroundColor?

### ISSUE THREAD

**Issue by hellofriday** [Prozi/pixi-shim#19]
hello,
My code is below
``` js
const PIXI = require("pixi-shim/pixi.js");

const app = new PIXI.Application({ width: 200, height: 200, backgroundColor: 0x061639, preserveDrawingBuffer: true });
const bunny = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAlCAYAAABcZvm2AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAWNJREFUeNrsV8sNwjAMbUqBBWACxB2pQ8AKcGALTsAJuDEFB1gBhuDAuWICmICPQh01pXWdJqEFcaglRGRbfonjPLuMc+5QwhjLGEJfZusjxZOL9akZKye9G98vPMfvsAx4qBfKwfzBL9s6uUHpI6U/u7+BKGkNb/H6umtk7MczF0HyfKS4zo/k/4AgTV8DOizrqX8oECgC+MGa8lGJp9sJDiAB8nyqYoglvJOPbP97IqoATGxWVZeXJlMQwYHA3piF8wJIblOVNBBxe3TPMLoHIKtxrbS7AAbBrA4Y5NaPAXf8LjN6wKZ0RaZOnlAFZnuXInVR4FTE6eYp0olPhhshtXsAwY3PquoAJNkIY33U7HTs7hYBwV24ItUKqDwgKF3VzAZ6k8HF+B1BMF8xRJbeJoqMXHZAAQ1kwoluURCdzepEugGEImBrIADB7I4lyfbJLlw92FKE6b5hVd+ktv4vAQYASMWxvlAAvcsAAAAASUVORK5CYII='
function createImage() {
    const image = document.createElement("img");

    image.src = bunny;

    return image;
}
const image = createImage();
const sprite = PIXI.Sprite.from(image.src);
sprite.width = 100
sprite.height = 100
const { width, height } = sprite
console.log(width, height)
app.stage.addChild(sprite);
app.render()

const base64 = app.view.toDataURL("image/png", 1);
const res = base64.replace(/^data:image\/png;base64,/, "")
require("fs").writeFile("out1.png", res, 'base64', (err) =>{
    console.log( err);
})
```
the result  
![out1](https://user-images.githubusercontent.com/7859030/123517160-0d53bd00-d6d2-11eb-9242-e80e7e8611ed.png)

Is it wrong?

**Comment by hellofriday** [comment]
dependencies version is 
    "canvas": "2",
    "pixi-shim": "^2.3.1",
    "pixi.js-legacy": "^6.0.4"

**Comment by Prozi** [comment]
@hellofriday i am looking into it

Looks like sprite is not properly loaded as its width and height is 1x1

When using for example loadImage from canvas package the image is correctly loaded and has correct dimensions but it cant be consumed by sprite.from(canvasImage)

Will try to make it work. It may take some time...

**Comment by Prozi** [comment]
If you remove

```
sprite.width = 100
sprite.height = 100
```

You will see in the logs

**Comment by Prozi** [comment]
unfortunately even after today's fight the issue persists

see my todays comment in https://github.com/Prozi/pixi-shim/issues/23

some progress has been made but I feel we've reached a wall

**Comment by Prozi** [comment]
cc @hellofriday

**Comment by Prozi** [comment]
closing as working and tested (with simple sprites)

a bit hackish but works, see:

https://github.com/Prozi/pixi-shim/blob/master/pixi.spec.js
https://github.com/Prozi/pixi-shim/blob/master/to-data-url.js

**Comment by hellofriday** [comment]
Thanks for your working，we use pixi in puppeteer for the needs.
