### ISSUE TITLE
Can not use Sprite.FromImage()

### ISSUE THREAD

**Issue by xiaobebe** [Prozi/pixi-shim#2]
Can not use Sprite.FromImage()

**Comment by Prozi** [comment]
I just checked

ran

```
node
new require('pixi-shim').Sprite.fromImage('')
```

it works

how are you trying to do it?

**Comment by Prozi** [comment]
@xiaobebe reopen if it doesnt work as I wrote

**Comment by yyman001** [comment]
![image](https://user-images.githubusercontent.com/5688485/52991177-87127680-3446-11e9-8e87-59c54bb249e8.png)
i need create sprite for node, is fail
