### ISSUE TITLE
How to use pixi layers with pixi shim?

### ISSUE THREAD

**Issue by LuisUrrutia** [Prozi/pixi-shim#22]
I tried to use pixi layers with pixi shims, but I always get this error:

`Error: Cannot find module '@pixi/display'`

I tried to import it with require:
```
const PIXI = require("pixi-shim");
const layers = require("@pixi/layers")
```

**Comment by Prozi** [comment]
try like this

``
require('pixi-shim')
const PIXI = require('pixi.js-legacy')
const layers = require("@pixi/layers")
```

@LuisUrrutia
