### ISSUE TITLE
Why doesn't `canvas.toDataURL()` work?

### ISSUE THREAD

**Issue by SmartArray** [Prozi/pixi-shim#31]
This one is too hacky. It won't be able to render complex use cases:
https://github.com/Prozi/pixi-shim/blob/b8e77bd51a06cbb6696330c6abd97fa463386e9f/to-data-url.js#L34

Can you answer why the result of `getDataURL()` only includes the canvas color and not the sprites?
Is there something that we have to change so that the server renders all graphics on to the canvas?

**Comment by Prozi** [comment]
in short, it doesnt work because of differences between nodejs Image and img for pixi consumption

**Comment by SmartArray** [comment]
Ah ok, thank you!
