### ISSUE TITLE
It is recommended to add webgl support.

### ISSUE THREAD

**Issue by sbfkcel** [Prozi/pixi-shim#5]
It is recommended to add webgl support.
Otherwise many features will not be better supported.

Node webgl support library：
node-webgl、gl

**Comment by Prozi** [comment]
please specify what benefit would this add to nodejs pixi shim @sbfkcel

**Comment by sbfkcel** [comment]
Better computing speed. The filter effect is also perfectly supported (this is unmatched by most other graphics libraries).

**Comment by Prozi** [comment]
@sbfkcel please test latest version (1.7.0) I added webgl and tried not to break things up

some features work some dont. pixi does.

please test and provide feedback if you can
