### ISSUE TITLE
Can't get Spring.from or Texture.from working

### ISSUE THREAD

**Issue by daviddawson** [Prozi/pixi-shim#7]
I'm trying to display some images and then view them via a data uri export of the canvas.

I can do text, shapes etc, but when I interact with the Loader, it either hangs (if I try to make it load) or it just has nothing on screen.  Not sure where to look...

```
const PIXI = require('pixi-shim')
const app = new PIXI.Application({
      backgroundColor: 0x1099bb,
      width: 1000,
      height: 1000
    });
// pulled from old issue, breaks immediately with "app.stage.addChild(new (require('pixi-shim') as any).Sprite.fromImage('cas.png'));"
// app.stage.addChild(new (require('pixi-shim') as any).Sprite.fromImage('cas.png'));
// executes, but I get nothing on the canvas
app.stage.addChild(PIXI.Sprite.from(tex));

// Some random thing, this works ok
const graphics = new PIXI.Graphics();
graphics.beginFill(0xDE3249);
graphics.drawRect(500, 50, 100, 100);
graphics.endFill();
app.stage.addChild(graphics);

app.render() // not seen in any examples, but if this isn't here, the canvas is blank

const data = app.view.toDataURL("image/png", 1); // works, but only shows the geometry
```

Not sure what I'm doing wrong, as this feels like it should work.  Is there a race or requirements I've missed somewhere?

**Comment by Prozi** [comment]
pixi loader shim is currently not implemented @daviddawson 

feel free to open a pull request

**Comment by Prozi** [comment]
@daviddawson 

Hmm after investigating the issuse:

Be sure to call `app.renderer.render(app.stage);` before calling toDataURL

Reference: https://github.com/pixijs/pixi.js/issues/766

Working example: https://codepan.herokuapp.com/#/gist/0b6baccfcd8cedcc5cdaa4f505026196?pans=js,console

**Comment by Prozi** [comment]
closing due inactivity

**Comment by foxyblocks** [comment]
Was this ever resolved, I'm having the same issue while following [this example](https://github.com/Prozi/pixi-shim/blob/master/pixi.spec.js#L38-L48) from the specs. The link to the working example you had seems to be broken.
