### ISSUE TITLE
Provide full examples showcasing PIXI's features running in node

### ISSUE THREAD

**Issue by jedateach** [Prozi/pixi-shim#9]
If we provide developers with rich examples that they can use as a starting point, it's more likely devs will be able to pick up this library easily, which can ultimately help with gaining contribution efforts.

The README and test.js files currently show very minimal examples. It would be great if they showcased the extents of what can be achieved with PIXI in a node environment.

**Comment by Prozi** [comment]
Well to be honest anything can be achieved.

Like:
* create a frontend game with pixijs
* decide to add multiplayer with nodejs and socketio
* move logic to backend (without removing pixi)
* everything still works

**Comment by Prozi** [comment]
What kind of examples do you have in mind? The idea is good overall

**Comment by jedateach** [comment]
I was just thinking something as basic as "this code will render some primitive objects via node".

But could be as complex as you like.

If there are caveats to using pixi in this way, perhaps they could be highlighted in code, if appropriate. Are there any PIXI concepts that won't work in node?

This might help for reference: https://github.com/CreateJS/EaselJS-NodeJS/tree/master/examples

**Comment by Prozi** [comment]
@jedateach does this resolve kinda your problem?

https://github.com/Prozi/pixi-shim/blob/master/index.spec.js

**Comment by Prozi** [comment]
also https://github.com/Prozi/pixi-shim/blob/master/pixi.spec.js

**Comment by Prozi** [comment]
Will work on this next week to have it properly reflected in the docs

**Comment by Prozi** [comment]
closing as tests and readme has been updated since multiple times.

the goal of this library is not to emulate pixi in nodejs

it is to be able to run code using pixi in node (example: make a game frontend, decide it should be multiplayer, add nodejs, plugin pixi-shim, still works)
